application: antachsite-hrd
version: 1
runtime: python
api_version: 1


handlers:


- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /
  static_files: index.html
  upload: index.html
