application: antachsite-hrd
version: migrate-python27
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /
  static_files: index.html
  upload: index.html
